blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])

blog/forms.py
from django import forms

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post
from django.views.generic import ListView
from .forms import EmailPostForm
from django.core.mail import send_mail

def post_list(request):
    # posts=Post.published.all()
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page':page,
                                                   'posts':posts})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginator_by = 3
    template_name = 'blog/post/list.html'

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    return render(request, 'blog/post/detail.html', {'post':post})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url,cd['comments'],cd['comments'])
            send_mail=(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

blog/templates/blog/base.html
{%load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'my_style.css'%}">
  </head>
  <body>
    <div class="container-fluid">
    <div class="margin-top">
      {% block content %}
      {% endblock %}
    </div>
    </div>
  </body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <div class="panel panel-success">
    <div class="panel-heading">
      <h1>{{ post.title }}</h1>
    </div>
    <div class="panel-body">
      <div class=" panel panel-success">
        <div class="container-fluid">
          <p class="margin-top">Published {{ post.publish }} by {{ post.author }}</p>
          {{ post.body|linebreaks }}
          <p><a href="{% url "blog:post_share" post.id %}">Share this post</a></p>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <div class="panel panel-success">
    <div class="panel-heading">
      <h1>My Blog</h1>
    </div>
    <div class="panel-body">
      {% for post in posts %}
      <div class=" panel panel-success">
        <div class="container-fluid">
          <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
          <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
          {{ post.body|truncatewords:30|linebreaks }}
        </div>
      </div>
      {% endfor %}
      {% include "pagination.html" with page=posts %}
    </div>
  </div>

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
  <div class="panel panel-success">
    <div class="panel-heading">
      <h1>E-mail successfully sent</h1>
    </div>
    <div class="panel-body">
      <div class=" panel panel-success">
        <div class="container-fluid">
          <p class="margin-top">
            "{{ post.title }}" was successfully sent by e-mail.
          </p>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="panel panel-success">
    <div class="panel-heading">
      <h1>Share "{{ post.title }}" by e-mail</h1>
    </div>
    <div class="panel-body">
      <div class=" panel panel-success">
        <div class="container-fluid">
          <form action="." method="post" class="margin-top panel-success">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-success" value="Send e-mail">
          <br><br>
          </form>
        </div>
      </div>
    </div>
  </div>

    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}

    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>

    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>